FROM {{fabric_compose.orderer.image}}

ARG genesis_file_path
ARG msp_path
ARG tls_path

ADD $genesis_file_path /var/hyperledger/orderer/
ADD $msp_path /var/hyperledger/orderer/msp/
ADD $tls_path /var/hyperledger/orderer/tls/

